### ISSUE TITLE
[HELP] Why that blackbox magic humby bumby? Let us come up with transparent approaches, please!

### ISSUE THREAD

**Issue by TimSusa** [DiscoNova/traktor-metadata-samples#17]
Hello Bro, 

I already read a lot on your websites, I like your work and I would like to push the community forward here. Sry my question I do not understand your doing that secret.. I do not like your blackbox. Let us just find a transparant way together, what would you say? 

[Approach with Icecast Parser](https://github.com/ghaiklor/icecast-parser/issues/184)

JFI# https://github.com/svandragt

**Comment by DiscoNova** [comment]
The main reason for the "black box" -approach is that the code for the original version of Traktor Metadata Tweeter, as it was known back in 2009, was written on company time as part of a project I was working on at the time. Therefore the original code is essentially the property of that company, and unfortunately, I am not at liberty to release the source code - even though it is of no practical use to the old company.

Similarly, since I am the one who originally wrote the code, I can't exactly take the proprietary solution and recreate it in some other way without fearing that my mere involvement would taint any possible open-source -worthiness of the new solution. Because of this, the "black box" -approach seemed like a suitable middle ground; the code uses my original IceCast protocol handler and the relatively efficient Ogg/Vorbis stream parsing ... Over a decade ago, the code was optimized to be efficient on the consumer hardware of the time, and the major moving parts have not changed significantly. With the improvement in computing power, it is _still_ stable and does its thing with minimal overhead.

Of course, the main problem of this approach has been that my shortsightedness **has** cursed the end-users regarding the possible use cases.

Versions 0.1 -> 0.4 were limited to "tweeting" the artist/track. Unfortunately for me, Twitter removed the username/password authentication from their API, but ... the application still "worked" - it just was unable to perform its primary function successfully ☺️

Between 2009 and 2018, users did come up with exciting workarounds; the most common one was creating a simple log watcher and parsing the end of the application's log file to grab the current artist/track from there and use it as they please.

In 2018 I had enough spare time to release version 0.5 of the application. This time the idea was to not lock the primary function to something I thought it should be doing - instead, v0.5's main new feature was an API for third parties. Well, two APIs actually, the REST-API and the JavaScript-API, which used the REST endpoints. But, once again, my lack of vision of the future prevailed, and I couldn't foresee that browsers (the intended most common target client) would become rigorous in script safety so soon afterward. Since I had failed to add CORS -headers into v0.5, again, what worked when released, soon stopped working since clients were unable to "mix and match" the API code and third party own code properly. Because of this, the current state of the samples repository is what it is; an attempt to overcome my earlier shortsightedness.

Recently I have been working on v0.6 of the listener -component, making it easier to inject third-party code into the same REST endpoints as the rest of the API.

**Comment by DiscoNova** [comment]
Some history links... in case past discussion is of interest ;)

https://www.native-instruments.com/forum/threads/94911/
https://www.native-instruments.com/forum/threads/341593/

**Comment by DiscoNova** [comment]
A quick writeup @ https://github.com/DiscoNova/traktor-metadata-samples/wiki

**Comment by TimSusa** [comment]
Thanks a lot, I had that already.. and fiddle much arround, learned so much and now I am quite happy as I have  a working hack. The magic is out for me and I can even go more detail there with an app anyhow it works for me fine :-)

https://github.com/TimSusa/traktor-meta-to-butt/blob/master/README.md

Feel free to give your personal statement... at least my invention are two lines of bash script. LOL 

PS: I saw in your text that you already know the approach. Yea I mean BUTT is so special software and if you offer to watch a textfile for you and even parse it out to their app, it might sounds like a schools kid solution parsing from the commandline and putting there in here.. I see, however I saved time. 

I think I see if liquidSOAP is good to go, otherewise fiddling a nodejs express server together with parserers wired.. it is just a matter of time to get such a thing ready. 

You could even do something like Tauri or NodeGUI with it to make an own app of it. As Virtual DJ is just putting a transcoding server in between as the only company helping their users here (300 Bugs no), Yes there might even be now still a potential for a commercial solution. The other thing maybe NI makes more API functoin to outside available and Qt Quick is not that bad.. how ever I have much respekt you did lot of good work, said for your self time is changing.. so yea.. l


HAPPY NEW YEAR!

**Comment by DiscoNova** [comment]
First of all, sorry that it has taken me so long to respond - I was spending holidays at the cottage and hadn't truly been paying attention to the net.

The reason the company I used to work for decided to create the Traktor Metadata Listener was, frankly, to **not** need to use "black box" third-party ShoutCast/IceCast servers. What we ended up doing was - creating our own "black box" solution. At the time, that didn't matter because it was "our" black box.

Regarding Your solution, in just those few lines of code, You've actually managed to rather literally recreate the original "m-nus" -answer to Richie Hawtin's original issue; _"I'm playing something with Traktor, how do I tell the audience what I am playing?"_ ... The initial solution was written the way it was because "it was much easier and quicker to use the icecast server to do the work" _(Yes - I still do love the fact that I have the original messages on my server to show that the originators of the **idea** wanted to ask me how I managed to do that)_
